#!/usr/bin/env python3
"""
Trace Kernel Diff Tool

Compares two trace analysis Excel files (generated by trace_module_analyzer.py) to identify
kernel replacements, additions, and removals between ROCm/SGLang image versions.

Strategy:
  1. Parse all Layer_N sheets from both files
  2. Match layers: first by index (Layer_N <-> Layer_N), then by type for unmatched
  3. Compute per-pair diffs; skip pairs with length ratio > 3x
  4. Group results by (layer_type, stage); pick highest-confidence pair as representative
  5. Report summary + per-type diff tables

Usage:
    python compare_traces.py file_a.xlsx file_b.xlsx [--output diff_report.xlsx] [--verbose]
"""

import argparse
import collections
import difflib
import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import openpyxl
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter


# ── Constants ────────────────────────────────────────────────────────────────

LENGTH_RATIO_THRESHOLD = 3.0


# ── Data structures ──────────────────────────────────────────────────────────

@dataclass
class KernelInfo:
    short_name: str
    kernel_name: str
    kernel_type: str


@dataclass
class LayerInfo:
    layer_idx: int
    layer_type: str
    stage: str
    kernels: List[KernelInfo]

    @property
    def short_name_tuple(self) -> Tuple[str, ...]:
        return tuple(k.short_name for k in self.kernels)

    @property
    def type_stage(self) -> Tuple[str, str]:
        return (self.layer_type, self.stage)


@dataclass
class DiffEntry:
    pos: int
    file_a_short: Optional[str]
    file_a_kernel: Optional[str]
    file_b_short: Optional[str]
    file_b_kernel: Optional[str]
    status: str  # SAME, REPLACED, ADDED, REMOVED


@dataclass
class PairResult:
    """Result of comparing one layer pair."""
    layer_a: LayerInfo
    layer_b: LayerInfo
    status: str  # IDENTICAL, CHANGED, LENGTH_MISMATCH
    entries: List[DiffEntry] = field(default_factory=list)
    similarity: float = 0.0  # fraction of SAME entries (0-1)
    match_method: str = "index"  # "index" or "type"


@dataclass
class GroupResult:
    """Aggregated result for one (layer_type, stage) group."""
    layer_type: str
    stage: str
    status: str  # IDENTICAL, CHANGED, LENGTH_MISMATCH, ONLY_IN_A, ONLY_IN_B
    # Per-pair stats
    n_pairs: int = 0
    n_identical: int = 0
    n_changed: int = 0
    n_skipped: int = 0
    # Representative diff (from highest-confidence changed pair)
    representative: Optional[PairResult] = None
    # Layers only in one file
    only_layers: List[LayerInfo] = field(default_factory=list)
    # Skipped pairs for reporting
    skipped_pairs: List[PairResult] = field(default_factory=list)

    @property
    def change_summary(self) -> str:
        if self.status == "IDENTICAL":
            return "-"
        if self.status in ("ONLY_IN_A", "ONLY_IN_B"):
            n = len(self.only_layers)
            return f"({n} layer{'s' if n != 1 else ''})"
        if self.status == "LENGTH_MISMATCH":
            return f"all {self.n_skipped} pair{'s' if self.n_skipped != 1 else ''} skipped"
        # CHANGED
        if not self.representative:
            return "-"
        counts = collections.Counter(
            e.status for e in self.representative.entries if e.status != "SAME"
        )
        parts = []
        for s in ("REPLACED", "ADDED", "REMOVED"):
            if counts[s]:
                parts.append(f"{counts[s]} {s.lower()}")
        return ", ".join(parts) or "-"


# ── Step 1: Parse Excel ─────────────────────────────────────────────────────

_HEADER_RE = re.compile(r"Layer\s+\d+\s+\(([^,]+),\s*(\w+)\)")


def parse_excel(filepath: str, verbose: bool = False) -> Dict[int, LayerInfo]:
    """Parse an analysis Excel file and return layers indexed by layer number."""
    wb = openpyxl.load_workbook(filepath, read_only=True)
    layers: Dict[int, LayerInfo] = {}

    for sheet_name in wb.sheetnames:
        if not sheet_name.startswith("Layer_"):
            continue

        ws = wb[sheet_name]
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            continue

        header_text = str(rows[0][0]) if rows[0][0] else ""
        m = _HEADER_RE.match(header_text)
        if not m:
            if verbose:
                print(f"  Warning: Could not parse header in {sheet_name}: {header_text!r}")
            continue

        layer_type = m.group(1).strip()
        stage = m.group(2).strip()
        layer_idx = int(sheet_name.split("_")[1])

        # Find data table
        data_start = None
        for i, row in enumerate(rows):
            if row[0] == "#" and row[4] == "Short Name":
                data_start = i + 1
                break

        if data_start is None:
            if verbose:
                print(f"  Warning: No data table found in {sheet_name}")
            continue

        kernels = []
        for row in rows[data_start:]:
            if row[0] is None or row[0] == "=== BREAKDOWN ===":
                break
            short_name = str(row[4]) if row[4] else ""
            kernel_name = str(row[5]) if row[5] else ""
            kernel_type = str(row[3]) if row[3] else ""
            kernels.append(KernelInfo(short_name, kernel_name, kernel_type))

        layers[layer_idx] = LayerInfo(layer_idx, layer_type, stage, kernels)

    wb.close()
    return layers


# ── Step 2: Match layers ────────────────────────────────────────────────────

def match_layers(
    layers_a: Dict[int, LayerInfo],
    layers_b: Dict[int, LayerInfo],
    verbose: bool = False,
) -> Tuple[List[Tuple[LayerInfo, LayerInfo, str]], List[LayerInfo], List[LayerInfo]]:
    """
    Match layers between two files.
    Returns: (matched_pairs, only_in_a, only_in_b)
    Each matched pair is (layer_a, layer_b, match_method).
    """
    matched = []
    unmatched_a: Dict[int, LayerInfo] = {}
    unmatched_b: Dict[int, LayerInfo] = {}
    used_a = set()
    used_b = set()

    # Phase 1: Direct index matching
    all_indices = sorted(set(layers_a.keys()) | set(layers_b.keys()))
    index_match_count = 0
    index_mismatch_count = 0

    for idx in all_indices:
        in_a = idx in layers_a
        in_b = idx in layers_b

        if in_a and in_b:
            a = layers_a[idx]
            b = layers_b[idx]
            if a.type_stage == b.type_stage:
                matched.append((a, b, "index"))
                used_a.add(idx)
                used_b.add(idx)
                index_match_count += 1
            else:
                # Type mismatch at this index — defer to Phase 2
                unmatched_a[idx] = a
                unmatched_b[idx] = b
                index_mismatch_count += 1
        elif in_a:
            unmatched_a[idx] = layers_a[idx]
        else:
            unmatched_b[idx] = layers_b[idx]

    if verbose:
        total = len(all_indices)
        print(f"  Index matching: {index_match_count}/{total} matched, "
              f"{index_mismatch_count} type mismatches, "
              f"{len(unmatched_a) - index_mismatch_count} only-in-A, "
              f"{len(unmatched_b) - index_mismatch_count} only-in-B")

    # Phase 2: Type-based matching for unmatched layers
    # Group unmatched by (type, stage), then match by occurrence order
    ua_by_type: Dict[Tuple[str, str], List[LayerInfo]] = {}
    ub_by_type: Dict[Tuple[str, str], List[LayerInfo]] = {}
    for layer in unmatched_a.values():
        ua_by_type.setdefault(layer.type_stage, []).append(layer)
    for layer in unmatched_b.values():
        ub_by_type.setdefault(layer.type_stage, []).append(layer)

    # Sort within each group by layer index for stable matching
    for v in ua_by_type.values():
        v.sort(key=lambda l: l.layer_idx)
    for v in ub_by_type.values():
        v.sort(key=lambda l: l.layer_idx)

    type_match_count = 0
    remaining_only_a = []
    remaining_only_b = []

    all_type_keys = sorted(set(ua_by_type.keys()) | set(ub_by_type.keys()))
    for key in all_type_keys:
        a_list = ua_by_type.get(key, [])
        b_list = ub_by_type.get(key, [])

        # Match 1st<->1st, 2nd<->2nd, etc.
        for i in range(min(len(a_list), len(b_list))):
            matched.append((a_list[i], b_list[i], "type"))
            type_match_count += 1

        # Leftovers
        if len(a_list) > len(b_list):
            remaining_only_a.extend(a_list[len(b_list):])
        elif len(b_list) > len(a_list):
            remaining_only_b.extend(b_list[len(a_list):])

    if verbose and type_match_count > 0:
        print(f"  Type-based matching: {type_match_count} additional pairs matched")
    if verbose and (remaining_only_a or remaining_only_b):
        print(f"  Unmatched: {len(remaining_only_a)} only-in-A, "
              f"{len(remaining_only_b)} only-in-B")

    return matched, remaining_only_a, remaining_only_b


# ── Step 3: Per-pair diff ───────────────────────────────────────────────────

def diff_pair(a: LayerInfo, b: LayerInfo, match_method: str) -> PairResult:
    """Compute diff for one layer pair."""
    len_a = len(a.kernels)
    len_b = len(b.kernels)
    ratio = max(len_a, len_b) / max(min(len_a, len_b), 1)

    if ratio > LENGTH_RATIO_THRESHOLD:
        return PairResult(a, b, "LENGTH_MISMATCH", similarity=0.0,
                          match_method=match_method)

    if a.short_name_tuple == b.short_name_tuple:
        return PairResult(a, b, "IDENTICAL", similarity=1.0,
                          match_method=match_method)

    entries = _diff_kernel_sequences(a, b)
    n_same = sum(1 for e in entries if e.status == "SAME")
    similarity = n_same / len(entries) if entries else 0.0

    return PairResult(a, b, "CHANGED", entries=entries, similarity=similarity,
                      match_method=match_method)


def _diff_kernel_sequences(a: LayerInfo, b: LayerInfo) -> List[DiffEntry]:
    """Build a diff table from two layers using SequenceMatcher."""
    seq_a = list(a.short_name_tuple)
    seq_b = list(b.short_name_tuple)
    infos_a = a.kernels
    infos_b = b.kernels

    matcher = difflib.SequenceMatcher(None, seq_a, seq_b)
    entries = []
    pos = 0

    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == "equal":
            for ai, bi in zip(range(i1, i2), range(j1, j2)):
                pos += 1
                entries.append(DiffEntry(
                    pos=pos,
                    file_a_short=seq_a[ai],
                    file_a_kernel=infos_a[ai].kernel_name,
                    file_b_short=seq_b[bi],
                    file_b_kernel=infos_b[bi].kernel_name,
                    status="SAME",
                ))
        elif tag == "replace":
            la = i2 - i1
            lb = j2 - j1
            for k in range(max(la, lb)):
                pos += 1
                a_idx = i1 + k if k < la else None
                b_idx = j1 + k if k < lb else None
                if a_idx is not None and b_idx is not None:
                    entries.append(DiffEntry(
                        pos=pos,
                        file_a_short=seq_a[a_idx],
                        file_a_kernel=infos_a[a_idx].kernel_name,
                        file_b_short=seq_b[b_idx],
                        file_b_kernel=infos_b[b_idx].kernel_name,
                        status="REPLACED",
                    ))
                elif a_idx is not None:
                    entries.append(DiffEntry(
                        pos=pos,
                        file_a_short=seq_a[a_idx],
                        file_a_kernel=infos_a[a_idx].kernel_name,
                        file_b_short=None, file_b_kernel=None,
                        status="REMOVED",
                    ))
                else:
                    entries.append(DiffEntry(
                        pos=pos,
                        file_a_short=None, file_a_kernel=None,
                        file_b_short=seq_b[b_idx],
                        file_b_kernel=infos_b[b_idx].kernel_name,
                        status="ADDED",
                    ))
        elif tag == "insert":
            for bi in range(j1, j2):
                pos += 1
                entries.append(DiffEntry(
                    pos=pos,
                    file_a_short=None, file_a_kernel=None,
                    file_b_short=seq_b[bi],
                    file_b_kernel=infos_b[bi].kernel_name,
                    status="ADDED",
                ))
        elif tag == "delete":
            for ai in range(i1, i2):
                pos += 1
                entries.append(DiffEntry(
                    pos=pos,
                    file_a_short=seq_a[ai],
                    file_a_kernel=infos_a[ai].kernel_name,
                    file_b_short=None, file_b_kernel=None,
                    status="REMOVED",
                ))

    return entries


# ── Step 4: Group results & select representative ───────────────────────────

def group_and_select(
    pair_results: List[PairResult],
    only_in_a: List[LayerInfo],
    only_in_b: List[LayerInfo],
    verbose: bool = False,
) -> List[GroupResult]:
    """Group per-pair results by (layer_type, stage) and pick representative."""
    # Group pair results
    groups: Dict[Tuple[str, str], List[PairResult]] = {}
    for pr in pair_results:
        key = pr.layer_a.type_stage
        groups.setdefault(key, []).append(pr)

    # Group only-in layers
    only_a_groups: Dict[Tuple[str, str], List[LayerInfo]] = {}
    only_b_groups: Dict[Tuple[str, str], List[LayerInfo]] = {}
    for layer in only_in_a:
        only_a_groups.setdefault(layer.type_stage, []).append(layer)
    for layer in only_in_b:
        only_b_groups.setdefault(layer.type_stage, []).append(layer)

    all_keys = sorted(
        set(groups.keys()) | set(only_a_groups.keys()) | set(only_b_groups.keys())
    )

    results = []
    for key in all_keys:
        layer_type, stage = key
        pairs = groups.get(key, [])
        oa = only_a_groups.get(key, [])
        ob = only_b_groups.get(key, [])

        if not pairs and not oa and not ob:
            continue

        # No matched pairs — only in one file
        if not pairs:
            if oa and not ob:
                results.append(GroupResult(layer_type, stage, "ONLY_IN_A",
                                          only_layers=oa))
            elif ob and not oa:
                results.append(GroupResult(layer_type, stage, "ONLY_IN_B",
                                          only_layers=ob))
            else:
                # Both have unmatched — shouldn't happen normally
                results.append(GroupResult(layer_type, stage, "ONLY_IN_A",
                                          only_layers=oa))
                results.append(GroupResult(layer_type, stage, "ONLY_IN_B",
                                          only_layers=ob))
            continue

        # Classify pairs
        identical = [p for p in pairs if p.status == "IDENTICAL"]
        changed = [p for p in pairs if p.status == "CHANGED"]
        skipped = [p for p in pairs if p.status == "LENGTH_MISMATCH"]

        n_pairs = len(pairs)
        n_identical = len(identical)
        n_changed = len(changed)
        n_skipped = len(skipped)

        valid = identical + changed

        if not valid:
            # All pairs skipped
            gr = GroupResult(layer_type, stage, "LENGTH_MISMATCH",
                             n_pairs=n_pairs, n_skipped=n_skipped,
                             skipped_pairs=skipped)
            # Add only-in layers if any
            gr.only_layers = oa + ob
            results.append(gr)
            continue

        if not changed:
            # All valid pairs are identical
            gr = GroupResult(layer_type, stage, "IDENTICAL",
                             n_pairs=n_pairs, n_identical=n_identical,
                             n_skipped=n_skipped, skipped_pairs=skipped)
            gr.only_layers = oa + ob
            results.append(gr)
            continue

        # Pick top-1 highest confidence (highest similarity among changed)
        representative = max(changed, key=lambda p: p.similarity)

        if verbose:
            print(f"  ({layer_type}, {stage}): {n_pairs} pairs — "
                  f"{n_identical} identical, {n_changed} changed, {n_skipped} skipped")
            print(f"    Representative: Layer_{representative.layer_a.layer_idx} <-> "
                  f"Layer_{representative.layer_b.layer_idx} "
                  f"(similarity: {representative.similarity:.1%})")
            if skipped:
                skipped_idx = [(p.layer_a.layer_idx, p.layer_b.layer_idx) for p in skipped]
                print(f"    Skipped pairs: {skipped_idx}")

        gr = GroupResult(layer_type, stage, "CHANGED",
                         n_pairs=n_pairs, n_identical=n_identical,
                         n_changed=n_changed, n_skipped=n_skipped,
                         representative=representative,
                         skipped_pairs=skipped)
        gr.only_layers = oa + ob
        results.append(gr)

    return results


# ── Step 5: Terminal output ──────────────────────────────────────────────────

def _truncate(s: Optional[str], width: int) -> str:
    if s is None:
        return "-"
    return s if len(s) <= width else s[: width - 1] + "…"


def output_terminal_report(
    groups: List[GroupResult], file_a: str, file_b: str, verbose: bool = False
) -> None:
    """Print the diff report to the terminal."""
    sep = "=" * 70
    print()
    print(sep)
    print("  Trace Kernel Diff Report")
    print(f"  File A: {file_a}")
    print(f"  File B: {file_b}")
    print(sep)

    # Summary table
    print()
    print("--- Layer Type Summary ---")
    col_lt = max(20, max((len(g.layer_type) for g in groups), default=10))
    col_st = max(8, max((len(g.stage) for g in groups), default=5))
    hdr = (f"  {'Layer Type':<{col_lt}} | {'Stage':<{col_st}} | "
           f"{'Status':<15} | {'Pairs':>5} | {'Skip':>4} | Changes")
    print(hdr)
    print(f"  {'-' * col_lt}-+-{'-' * col_st}-+-{'-' * 15}-+-{'-' * 5}-+-"
          f"{'-' * 4}-+-{'-' * 30}")

    for g in groups:
        pairs_str = str(g.n_pairs) if g.n_pairs else "-"
        skip_str = str(g.n_skipped) if g.n_skipped else "-"
        if g.status in ("ONLY_IN_A", "ONLY_IN_B"):
            pairs_str = "-"
            skip_str = "-"
        print(f"  {g.layer_type:<{col_lt}} | {g.stage:<{col_st}} | "
              f"{g.status:<15} | {pairs_str:>5} | {skip_str:>4} | {g.change_summary}")

    # Per group details
    for g in groups:
        if g.status == "IDENTICAL":
            continue

        print()
        print(f"--- {g.layer_type} ({g.stage}) — {g.status} ---")

        if g.status in ("ONLY_IN_A", "ONLY_IN_B"):
            label = "A" if g.status == "ONLY_IN_A" else "B"
            layers = g.only_layers
            print(f"  Present only in File {label} ({len(layers)} layer{'s' if len(layers) != 1 else ''})")
            if layers:
                idxs = sorted(l.layer_idx for l in layers)
                print(f"  Layer indices: {idxs}")
                # Show kernel sequence from first layer
                first = min(layers, key=lambda l: l.layer_idx)
                print(f"  Kernel sequence ({len(first.kernels)} kernels, from Layer_{first.layer_idx}):")
                for i, k in enumerate(first.kernels, 1):
                    print(f"    {i:3d}. {k.short_name}")
            continue

        if g.status == "LENGTH_MISMATCH":
            print(f"  All {g.n_skipped} pair{'s' if g.n_skipped != 1 else ''} had kernel count "
                  f"ratio > {LENGTH_RATIO_THRESHOLD:.0f}x — skipped")
            for p in g.skipped_pairs:
                la, lb = len(p.layer_a.kernels), len(p.layer_b.kernels)
                ratio = max(la, lb) / max(min(la, lb), 1)
                print(f"    Layer_{p.layer_a.layer_idx} ({la} kernels) <-> "
                      f"Layer_{p.layer_b.layer_idx} ({lb} kernels) — {ratio:.1f}x")
            print(f"  This usually means trace_analyzer packed multiple iterations into one layer sheet.")
            continue

        # CHANGED — show representative diff
        rep = g.representative
        print(f"  {g.n_pairs} pairs: {g.n_identical} identical, "
              f"{g.n_changed} changed, {g.n_skipped} skipped")
        print(f"  Representative: Layer_{rep.layer_a.layer_idx} <-> "
              f"Layer_{rep.layer_b.layer_idx} "
              f"(similarity: {rep.similarity:.1%}, match: {rep.match_method})")
        print()

        col_w = 25
        hdr_a = f"{'File A (old)':<{col_w}}"
        hdr_b = f"{'File B (new)':<{col_w}}"
        print(f"  {'#':>3} | {hdr_a} | {hdr_b} | Status")
        print(f"  {'-' * 3}-+-{'-' * col_w}-+-{'-' * col_w}-+-{'-' * 10}")
        for e in rep.entries:
            a_str = _truncate(e.file_a_short, col_w)
            b_str = _truncate(e.file_b_short, col_w)
            print(f"  {e.pos:3d} | {a_str:<{col_w}} | {b_str:<{col_w}} | {e.status}")

        if g.n_skipped and g.skipped_pairs:
            print()
            print(f"  Skipped pairs (length ratio > {LENGTH_RATIO_THRESHOLD:.0f}x):")
            for p in g.skipped_pairs:
                la, lb = len(p.layer_a.kernels), len(p.layer_b.kernels)
                ratio = max(la, lb) / max(min(la, lb), 1)
                print(f"    Layer_{p.layer_a.layer_idx} ({la}) <-> "
                      f"Layer_{p.layer_b.layer_idx} ({lb}) — {ratio:.1f}x")

        if verbose and rep.entries:
            changed_entries = [e for e in rep.entries if e.status != "SAME"]
            if changed_entries:
                print()
                print("  Full kernel names for changed entries:")
                for e in changed_entries:
                    print(f"    #{e.pos} [{e.status}]")
                    if e.file_a_kernel:
                        print(f"      A: {e.file_a_kernel}")
                    if e.file_b_kernel:
                        print(f"      B: {e.file_b_kernel}")

    print()


# ── Step 6: Excel output ────────────────────────────────────────────────────

_FILL_GREEN = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
_FILL_YELLOW = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")
_FILL_RED = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")
_FILL_BLUE = PatternFill(start_color="BDD7EE", end_color="BDD7EE", fill_type="solid")
_FILL_GRAY = PatternFill(start_color="D9D9D9", end_color="D9D9D9", fill_type="solid")
_FILL_HEADER = PatternFill(start_color="D9E2F3", end_color="D9E2F3", fill_type="solid")
_FONT_BOLD = Font(bold=True)
_FONT_TITLE = Font(bold=True, size=12)

_STATUS_FILLS = {
    "SAME": _FILL_GREEN,
    "REPLACED": _FILL_YELLOW,
    "REMOVED": _FILL_RED,
    "ADDED": _FILL_BLUE,
}

_GROUP_STATUS_FILLS = {
    "IDENTICAL": _FILL_GREEN,
    "CHANGED": _FILL_YELLOW,
    "ONLY_IN_A": _FILL_RED,
    "ONLY_IN_B": _FILL_BLUE,
    "LENGTH_MISMATCH": _FILL_GRAY,
}


def output_excel_report(
    groups: List[GroupResult], file_a: str, file_b: str, output_path: str
) -> None:
    """Write a color-coded Excel diff report."""
    wb = openpyxl.Workbook()

    # ── Summary sheet ──
    ws = wb.active
    ws.title = "Summary"

    ws.append(["Trace Kernel Diff Report"])
    ws["A1"].font = _FONT_TITLE
    ws.append([f"File A: {file_a}"])
    ws.append([f"File B: {file_b}"])
    ws.append([])

    headers = ["Layer Type", "Stage", "Status", "Pairs", "Skipped", "Changes"]
    ws.append(headers)
    for col_idx in range(1, len(headers) + 1):
        ws.cell(row=ws.max_row, column=col_idx).font = _FONT_BOLD
        ws.cell(row=ws.max_row, column=col_idx).fill = _FILL_HEADER

    for g in groups:
        pairs = g.n_pairs if g.n_pairs else "-"
        skipped = g.n_skipped if g.n_skipped else "-"
        if g.status in ("ONLY_IN_A", "ONLY_IN_B"):
            pairs = "-"
            skipped = "-"
        ws.append([g.layer_type, g.stage, g.status, pairs, skipped, g.change_summary])

        fill = _GROUP_STATUS_FILLS.get(g.status)
        if fill:
            ws.cell(row=ws.max_row, column=3).fill = fill

    _auto_width(ws)

    # ── Per group detail sheets ──
    for g in groups:
        if g.status == "IDENTICAL":
            continue

        raw_name = f"{g.layer_type} ({g.stage})"
        sheet_name = raw_name[:31]
        existing = {s.title for s in wb.worksheets}
        if sheet_name in existing:
            sheet_name = sheet_name[:28] + "_2"
        ws = wb.create_sheet(title=sheet_name)

        ws.append([f"{g.layer_type} ({g.stage}) — {g.status}"])
        ws["A1"].font = _FONT_TITLE

        if g.status in ("ONLY_IN_A", "ONLY_IN_B"):
            label = "A" if g.status == "ONLY_IN_A" else "B"
            ws.append([f"Present only in File {label} ({len(g.only_layers)} layers)"])
            ws.append([])

            if g.only_layers:
                first = min(g.only_layers, key=lambda l: l.layer_idx)
                detail_headers = ["#", "Short Name", "Kernel Name", "Type"]
                ws.append(detail_headers)
                for ci in range(1, len(detail_headers) + 1):
                    ws.cell(row=ws.max_row, column=ci).font = _FONT_BOLD
                    ws.cell(row=ws.max_row, column=ci).fill = _FILL_HEADER
                for i, ki in enumerate(first.kernels, 1):
                    ws.append([i, ki.short_name, ki.kernel_name, ki.kernel_type])
            _auto_width(ws)
            continue

        if g.status == "LENGTH_MISMATCH":
            ws.append([f"All {g.n_skipped} pairs skipped (kernel count ratio > "
                       f"{LENGTH_RATIO_THRESHOLD:.0f}x)"])
            ws.append([])
            for p in g.skipped_pairs:
                la, lb = len(p.layer_a.kernels), len(p.layer_b.kernels)
                ratio = max(la, lb) / max(min(la, lb), 1)
                ws.append([f"Layer_{p.layer_a.layer_idx} ({la} kernels) <-> "
                           f"Layer_{p.layer_b.layer_idx} ({lb} kernels) — {ratio:.1f}x"])
            _auto_width(ws)
            continue

        # CHANGED
        rep = g.representative
        ws.append([f"{g.n_pairs} pairs: {g.n_identical} identical, "
                   f"{g.n_changed} changed, {g.n_skipped} skipped"])
        ws.append([f"Representative: Layer_{rep.layer_a.layer_idx} <-> "
                   f"Layer_{rep.layer_b.layer_idx} "
                   f"(similarity: {rep.similarity:.1%}, match: {rep.match_method})"])
        ws.append([])

        detail_headers = ["Pos", "FileA_ShortName", "FileA_KernelName",
                          "FileB_ShortName", "FileB_KernelName", "Status"]
        ws.append(detail_headers)
        header_row = ws.max_row
        for ci in range(1, len(detail_headers) + 1):
            ws.cell(row=header_row, column=ci).font = _FONT_BOLD
            ws.cell(row=header_row, column=ci).fill = _FILL_HEADER

        for e in rep.entries:
            ws.append([
                e.pos,
                e.file_a_short or "-",
                e.file_a_kernel or "-",
                e.file_b_short or "-",
                e.file_b_kernel or "-",
                e.status,
            ])
            fill = _STATUS_FILLS.get(e.status)
            if fill:
                for ci in range(1, len(detail_headers) + 1):
                    ws.cell(row=ws.max_row, column=ci).fill = fill

        _auto_width(ws)

    wb.save(output_path)
    print(f"Excel report saved to: {output_path}")


def _auto_width(ws, max_width: int = 50) -> None:
    """Auto-adjust column widths based on content."""
    for col_cells in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col_cells[0].column)
        for cell in col_cells:
            if cell.value is not None:
                max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = min(max_len + 2, max_width)


# ── Main ────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Compare two trace analysis Excel files to identify kernel changes.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
Examples:
  python compare_traces.py old_analysis.xlsx new_analysis.xlsx
  python compare_traces.py old.xlsx new.xlsx --output diff_report.xlsx --verbose
""",
    )
    parser.add_argument("file_a", help="First (old) trace analysis Excel file")
    parser.add_argument("file_b", help="Second (new) trace analysis Excel file")
    parser.add_argument("--output", "-o", help="Output Excel diff report path")
    parser.add_argument("--verbose", "-v", action="store_true", help="Show detailed output")
    args = parser.parse_args()

    # Step 1: Parse
    print(f"Parsing File A: {args.file_a}")
    layers_a = parse_excel(args.file_a, verbose=args.verbose)
    print(f"  Found {len(layers_a)} layers")

    print(f"Parsing File B: {args.file_b}")
    layers_b = parse_excel(args.file_b, verbose=args.verbose)
    print(f"  Found {len(layers_b)} layers")

    # Step 2: Match layers
    print("\nMatching layers...")
    matched, only_a, only_b = match_layers(layers_a, layers_b, verbose=args.verbose)
    print(f"  {len(matched)} pairs matched, "
          f"{len(only_a)} only-in-A, {len(only_b)} only-in-B")

    # Step 3: Per-pair diff
    print("Computing per-pair diffs...")
    pair_results = []
    for a, b, method in matched:
        pr = diff_pair(a, b, method)
        pair_results.append(pr)

    n_id = sum(1 for p in pair_results if p.status == "IDENTICAL")
    n_ch = sum(1 for p in pair_results if p.status == "CHANGED")
    n_sk = sum(1 for p in pair_results if p.status == "LENGTH_MISMATCH")
    print(f"  {n_id} identical, {n_ch} changed, {n_sk} skipped (length mismatch)")

    # Step 4: Group and select representative
    if args.verbose:
        print("\nSelecting representatives...")
    group_results = group_and_select(pair_results, only_a, only_b, verbose=args.verbose)

    # Step 5: Terminal report
    output_terminal_report(group_results, args.file_a, args.file_b, verbose=args.verbose)

    # Step 6: Excel report (optional)
    if args.output:
        output_excel_report(group_results, args.file_a, args.file_b, args.output)


if __name__ == "__main__":
    main()
