#!/usr/bin/env bash
# Capture Claude Code + GPU + git state into memory/bridge/STATUS.md
# Usage:
#   remote_snapshot.sh --role container|host [--task "..."] [--note "..."] [--session-id UUID]
set -euo pipefail

AGENT_BOX_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"
REMOTE_DIR="$AGENT_BOX_DIR/memory/bridge"
SESSIONS_DIR="$REMOTE_DIR/sessions"
mkdir -p "$SESSIONS_DIR"

ROLE="unknown"
TASK=""
NOTE=""
SESSION_ID=""
RC_URL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --role) ROLE="$2"; shift 2 ;;
    --task) TASK="$2"; shift 2 ;;
    --note) NOTE="$2"; shift 2 ;;
    --session-id) SESSION_ID="$2"; shift 2 ;;
    --rc-url) RC_URL="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

HOSTNAME_FQ="$(hostname -f 2>/dev/null || hostname)"
TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
CWD="$(pwd)"
USER_NAME="$(whoami)"

# Detect container
IN_CONTAINER=0
if [[ -f /.dockerenv ]] || grep -q docker /proc/1/cgroup 2>/dev/null; then
  IN_CONTAINER=1
fi
CONTAINER_ID=""
if command -v docker >/dev/null 2>&1 && [[ "$IN_CONTAINER" -eq 0 ]]; then
  CONTAINER_ID="$(docker ps --format '{{.ID}} {{.Names}}' 2>/dev/null | head -5 || true)"
elif [[ -f /proc/self/cgroup ]]; then
  CONTAINER_ID="$(grep -oE '[0-9a-f]{64}' /proc/self/cgroup 2>/dev/null | head -1 || true)"
fi

# Git (best effort)
GIT_ROOT=""
GIT_BRANCH=""
GIT_DIRTY=""
if git rev-parse --show-toplevel >/dev/null 2>&1; then
  GIT_ROOT="$(git rev-parse --show-toplevel)"
  GIT_BRANCH="$(git branch --show-current 2>/dev/null || true)"
  GIT_DIRTY="$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')"
fi

# SGLang root
SGLANG_ROOT=""
SGLANG_ROOT="$(python3 -c "import sglang, pathlib; print(pathlib.Path(sglang.__file__).resolve().parents[2])" 2>/dev/null || true)"

# Claude session from ~/.claude/sessions
CLAUDE_SESSION=""
CLAUDE_STATUS=""
if [[ -d "${HOME}/.claude/sessions" ]]; then
  # newest busy session in cwd subtree
  CLAUDE_SESSION="$(python3 - <<'PY' 2>/dev/null || true
import json, os, glob
cwd = os.getcwd()
best = None
for p in glob.glob(os.path.expanduser("~/.claude/sessions/*.json")):
    try:
        d = json.load(open(p))
    except Exception:
        continue
    scwd = d.get("cwd", "")
    if not scwd or not (cwd.startswith(scwd) or scwd.startswith(cwd)):
        continue
    if d.get("status") in ("busy", "idle") or True:
        best = d
if best:
    print(best.get("sessionId", ""))
PY
)"
fi
if [[ -z "$SESSION_ID" && -n "$CLAUDE_SESSION" ]]; then
  SESSION_ID="$CLAUDE_SESSION"
fi

# GPU snapshot (MI355)
GPU_SNAPSHOT="unavailable"
if command -v rocm-smi >/dev/null 2>&1; then
  GPU_SNAPSHOT="$(rocm-smi --showuse --showmemuse 2>/dev/null | head -20 || echo 'rocm-smi failed')"
elif [[ -x "$AGENT_BOX_DIR/skills/gpu-status/gpu_status.py" ]]; then
  GPU_SNAPSHOT="$(python3 "$AGENT_BOX_DIR/skills/gpu-status/gpu_status.py" 2>/dev/null | head -15 || true)"
fi

# SGLang server
SERVER_SNAPSHOT=""
if command -v pgrep >/dev/null 2>&1; then
  SERVER_SNAPSHOT="$(pgrep -af 'sglang.launch_server' 2>/dev/null | head -3 || true)"
fi

# Write YAML sidecar
YAML_FILE="$SESSIONS_DIR/latest.yaml"
if [[ -n "$SESSION_ID" ]]; then
  YAML_FILE="$SESSIONS_DIR/${SESSION_ID}.yaml"
fi

cat > "$YAML_FILE" <<EOF
updated_at: "$TS"
role: $ROLE
hostname: $HOSTNAME_FQ
user: $USER_NAME
in_container: $IN_CONTAINER
container_hint: "$CONTAINER_ID"
cwd: $CWD
git_root: $GIT_ROOT
git_branch: $GIT_BRANCH
git_dirty_files: $GIT_DIRTY
sglang_root: $SGLANG_ROOT
claude_session_id: $SESSION_ID
remote_control_url: "$RC_URL"
task: "$TASK"
note: "$NOTE"
EOF

# Human-readable STATUS.md
{
  echo "# Remote Status"
  echo ""
  echo "> Auto-generated by \`remote_snapshot.sh\` at **$TS**"
  echo ""
  echo "| Field | Value |"
  echo "|---|---|"
  echo "| Role | \`$ROLE\` |"
  echo "| Host | \`$HOSTNAME_FQ\` |"
  echo "| User | \`$USER_NAME\` |"
  echo "| In container | $IN_CONTAINER |"
  echo "| CWD | \`$CWD\` |"
  echo "| Git | \`${GIT_BRANCH:-n/a}\` @ \`${GIT_ROOT:-n/a}\` (dirty: ${GIT_DIRTY:-0}) |"
  echo "| SGLang | \`${SGLANG_ROOT:-n/a}\` |"
  echo "| Claude session | \`${SESSION_ID:-n/a}\` |"
  if [[ -n "$RC_URL" ]]; then
    echo "| Remote Control | $RC_URL |"
  fi
  if [[ -n "$TASK" ]]; then
    echo "| **Current task** | $TASK |"
  fi
  if [[ -n "$NOTE" ]]; then
    echo "| Note | $NOTE |"
  fi
  echo ""
  echo "## GPU"
  echo '```'
  echo "$GPU_SNAPSHOT"
  echo '```'
  if [[ -n "$SERVER_SNAPSHOT" ]]; then
    echo ""
    echo "## SGLang server"
    echo '```'
    echo "$SERVER_SNAPSHOT"
    echo '```'
  fi
  echo ""
  echo "## Quick links"
  echo "- INBOX (host→container): [INBOX.md](INBOX.md)"
  echo "- OUTBOX (container→host): [OUTBOX.md](OUTBOX.md)"
  echo "- Sessions YAML: \`sessions/${SESSION_ID:-latest}.yaml\`"
  echo "- Claude sessions dir: \`~/.claude/sessions/\`"
} > "$REMOTE_DIR/STATUS.md"

ln -sf "$(basename "$YAML_FILE")" "$SESSIONS_DIR/latest.yaml" 2>/dev/null || cp -f "$YAML_FILE" "$SESSIONS_DIR/latest.yaml"

echo "[remote_snapshot] wrote $REMOTE_DIR/STATUS.md"
echo "[remote_snapshot] yaml: $YAML_FILE"
